---
- name: Installing multiple packages
  hosts: all
  become: true

  vars: 
    packages_name: 
      Ubuntu: apache2 
      Amazon: httpd


  tasks: 
    - name: Install packages on Ubuntu
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - apache2 
        - git 
        - nodejs
      when : ansible_distribution == "Ubuntu"

    - name: Installing packages on Al2
      yum: 
        name: "{{ item }}"
        state: present
      with_items: 
        - nginx
        - httpd
        - git 
        - nodejs
      when: ansible_distribution == "Amazon"